// prototype_history/output_prototype_AZ/frontend/src/pages/HomePage.jsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axiosInstance from '../api/axios.js';
import ProductCard from '../components/ProductCard.jsx';

export default function HomePage() {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    axiosInstance
      .get('/api/products')
      .then((res) => setProducts(res.data.slice(0, 8)))
      .catch(() => setError('Failed to load products.'))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div>
      {/* Hero Section */}
      <section className="relative bg-gradient-to-br from-brand-600 via-brand-700 to-brand-900 text-white overflow-hidden">
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-0 left-0 w-96 h-96 bg-white rounded-full -translate-x-1/2 -translate-y-1/2" />
          <div className="absolute bottom-0 right-0 w-80 h-80 bg-white rounded-full translate-x-1/3 translate-y-1/3" />
        </div>
        <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-24 md:py-32 text-center">
          <span className="inline-block bg-white/20 text-white text-xs font-semibold px-3 py-1 rounded-full mb-4 tracking-wide uppercase">
            Welcome to A2Z Selects
          </span>
          <h1 className="text-4xl md:text-6xl font-extrabold leading-tight mb-6">
            Discover Products
            <br />
            <span className="text-brand-200">You'll Love</span>
          </h1>
          <p className="text-lg md:text-xl text-brand-100 max-w-2xl mx-auto mb-10">
            Handpicked selections from A to Z — quality items curated just for you.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/products"
              className="inline-flex items-center justify-center px-8 py-3.5 rounded-xl bg-white text-brand-700 font-bold text-base hover:bg-brand-50 transition-colors shadow-lg"
            >
              Shop Now
            </Link>
            <a
              href="#featured"
              className="inline-flex items-center justify-center px-8 py-3.5 rounded-xl bg-white/10 text-white font-bold text-base hover:bg-white/20 transition-colors border border-white/30"
            >
              See Featured
            </a>
          </div>
        </div>
      </section>

      {/* Stats Bar */}
      <section className="bg-white border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="grid grid-cols-3 gap-4 text-center">
            <div>
              <p className="text-2xl font-extrabold text-brand-600">{products.length}+</p>
              <p className="text-xs text-gray-500 font-medium mt-0.5">Products</p>
            </div>
            <div>
              <p className="text-2xl font-extrabold text-brand-600">100%</p>
              <p className="text-xs text-gray-500 font-medium mt-0.5">Quality</p>
            </div>
            <div>
              <p className="text-2xl font-extrabold text-brand-600">A–Z</p>
              <p className="text-xs text-gray-500 font-medium mt-0.5">Selection</p>
            </div>
          </div>
        </div>
      </section>

      {/* Featured Products */}
      <section id="featured" className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="flex items-center justify-between mb-8">
          <div>
            <h2 className="text-2xl md:text-3xl font-extrabold text-gray-900">
              Featured Products
            </h2>
            <p className="text-gray-500 text-sm mt-1">Our latest and greatest picks</p>
          </div>
          <Link
            to="/products"
            className="text-brand-600 font-semibold text-sm hover:text-brand-700 transition-colors flex items-center gap-1"
          >
            View All
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
            </svg>
          </Link>
        </div>

        {loading && (
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-5">
            {Array.from({ length: 8 }).map((_, i) => (
              <div key={i} className="card animate-pulse">
                <div className="aspect-square bg-gray-200" />
                <div className="p-4 space-y-2">
                  <div className="h-4 bg-gray-200 rounded w-3/4" />
                  <div className="h-3 bg-gray-200 rounded w-1/2" />
                </div>
              </div>
            ))}
          </div>
        )}

        {error && (
          <div className="text-center py-16">
            <p className="text-red-500 font-medium">{error}</p>
          </div>
        )}

        {!loading && !error && products.length === 0 && (
          <div className="text-center py-20">
            <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg className="w-10 h-10 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4" />
              </svg>
            </div>
            <p className="text-gray-500 font-medium">No products yet.</p>
            <p className="text-gray-400 text-sm mt-1">Check back soon!</p>
          </div>
        )}

        {!loading && !error && products.length > 0 && (
          <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-5">
            {products.map((product) => (
              <ProductCard key={product.id} product={product} />
            ))}
          </div>
        )}
      </section>

      {/* CTA Banner */}
      <section className="bg-gradient-to-r from-brand-50 to-brand-100 border-y border-brand-200">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-14 text-center">
          <h2 className="text-2xl md:text-3xl font-extrabold text-brand-800 mb-3">
            Ready to find something special?
          </h2>
          <p className="text-brand-600 mb-7 text-base">
            Browse our full catalog and discover your next favorite item.
          </p>
          <Link to="/products" className="btn-primary px-8 py-3 text-base">
            Browse All Products
          </Link>
        </div>
      </section>
    </div>
  );
}

// prototype_history/starbucks_sim/frontend/src/pages/HomePage.vue
<template>
  <div>
    <!-- Hero Section -->
    <section class="bg-starbucks-dark-green text-white py-20 px-4 relative overflow-hidden">
      <div class="absolute inset-0 opacity-10">
        <div class="absolute top-10 left-10 text-9xl">☕</div>
        <div class="absolute bottom-10 right-10 text-9xl">🍵</div>
        <div class="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 text-9xl">🥤</div>
      </div>
      <div class="max-w-4xl mx-auto text-center relative z-10">
        <p class="text-starbucks-light-green text-sm font-medium tracking-widest uppercase mb-4">
          Welcome to
        </p>
        <h1 class="text-5xl md:text-7xl font-black mb-6 leading-tight">
          Starbucks<br />
          <span class="text-starbucks-gold">Order App</span>
        </h1>
        <p class="text-starbucks-light-green text-lg md:text-xl mb-10 max-w-2xl mx-auto">
          Craft your perfect drink. Order ahead. Skip the line.
        </p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center">
          <RouterLink to="/menu" class="btn-primary text-lg px-10 py-4">
            Order Now
          </RouterLink>
          <RouterLink
            v-if="!authStore.isAuthenticated"
            to="/register"
            class="btn-secondary text-lg px-10 py-4 border-white text-white hover:bg-white/10"
          >
            Join Rewards
          </RouterLink>
        </div>
      </div>
    </section>

    <!-- Featured Drinks -->
    <section class="max-w-7xl mx-auto px-4 py-16">
      <div class="flex items-center justify-between mb-8">
        <div>
          <h2 class="text-3xl font-black text-starbucks-brown">Featured Drinks</h2>
          <p class="text-gray-500 mt-1">Our most popular picks</p>
        </div>
        <RouterLink to="/menu" class="btn-ghost hidden sm:flex items-center gap-1">
          View all
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
          </svg>
        </RouterLink>
      </div>

      <!-- Loading -->
      <div v-if="menuStore.loading" class="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div v-for="i in 4" :key="i" class="card h-64 animate-pulse bg-gray-100" />
      </div>

      <!-- Drinks grid -->
      <div v-else class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        <DrinkCard
          v-for="drink in featuredDrinks"
          :key="drink.id"
          :drink="drink"
        />
      </div>

      <div class="text-center mt-8 sm:hidden">
        <RouterLink to="/menu" class="btn-secondary">View All Drinks</RouterLink>
      </div>
    </section>

    <!-- Categories Section -->
    <section class="bg-white py-16 px-4">
      <div class="max-w-7xl mx-auto">
        <h2 class="text-3xl font-black text-starbucks-brown mb-8 text-center">Browse by Category</h2>
        <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5 gap-4">
          <RouterLink
            v-for="cat in menuStore.categories"
            :key="cat.id"
            :to="`/menu?category=${cat.id}`"
            class="card p-6 text-center hover:border-starbucks-green border border-transparent group"
          >
            <div class="text-4xl mb-3">{{ categoryEmoji(cat.name) }}</div>
            <p class="font-bold text-starbucks-brown text-sm group-hover:text-starbucks-green transition-colors">
              {{ cat.name }}
            </p>
          </RouterLink>
        </div>
      </div>
    </section>

    <!-- Why Order Online -->
    <section class="max-w-7xl mx-auto px-4 py-16">
      <h2 class="text-3xl font-black text-starbucks-brown mb-10 text-center">Why Order Online?</h2>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-8">
        <div class="text-center">
          <div class="w-16 h-16 bg-starbucks-light-green rounded-full flex items-center justify-center text-3xl mx-auto mb-4">
            ⚡
          </div>
          <h3 class="font-bold text-starbucks-brown text-lg mb-2">Skip the Line</h3>
          <p class="text-gray-500 text-sm">Order ahead and pick up when it's ready. No waiting.</p>
        </div>
        <div class="text-center">
          <div class="w-16 h-16 bg-starbucks-light-green rounded-full flex items-center justify-center text-3xl mx-auto mb-4">
            🎨
          </div>
          <h3 class="font-bold text-starbucks-brown text-lg mb-2">Fully Customizable</h3>
          <p class="text-gray-500 text-sm">Choose your size, milk, and extras exactly how you like it.</p>
        </div>
        <div class="text-center">
          <div class="w-16 h-16 bg-starbucks-light-green rounded-full flex items-center justify-center text-3xl mx-auto mb-4">
            📱
          </div>
          <h3 class="font-bold text-starbucks-brown text-lg mb-2">Track Your Order</h3>
          <p class="text-gray-500 text-sm">Real-time status updates from pending to ready.</p>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { computed, onMounted } from 'vue'
import { RouterLink, useRoute } from 'vue-router'
import DrinkCard from '@/components/DrinkCard.vue'
import { useMenuStore } from '@/stores/menu.js'
import { useAuthStore } from '@/stores/auth.js'

const menuStore = useMenuStore()
const authStore = useAuthStore()

const featuredDrinks = computed(() => menuStore.drinks.slice(0, 8))

onMounted(async () => {
  await Promise.all([
    menuStore.fetchCategories(),
    menuStore.fetchDrinks()
  ])
})

function categoryEmoji(name) {
  const map = {
    'Hot Coffees': '☕',
    'Cold Brews': '🧊',
    'Teas': '🍵',
    'Refreshers': '🍹',
    'Frappuccinos': '🥤'
  }
  return map[name] || '☕'
}
</script>
